os:
    #    - osx
    - linux
sudo: false
before_install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh; fi
    - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh; fi
    - export PATH="$HOME/miniconda/bin:$PATH"
    - bash miniconda.sh -b -p $HOME/miniconda
    - conda config --set always_yes yes --set changeps1 no
script:
    - conda install -c cdat/label/nightly -c conda-forge -c cdat nose vcs mesalib nodejs vcs-js flask "cdms2>3.0.2018.08.28"
    - export UVCDAT_ANONYMOUS_LOG=False
    - echo $TRAVIS_BRANCH
    - export TRAVIS_PR_BRANCH=$TRAVIS_BRANCH
    - echo $TRAVIS_EVENT_TYPE
    - echo $TRAVIS_PULL_REQUEST
    - cd frontend
    - npm install
    - cd ..
    - python setup.py install
    - pip install -e .[test]
    - py.test --cov vcdat
    - cd frontend
    - npm run coverage
    - npm run coveralls
    - cd ..
after_success:
    - if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then conda install conda-build && conda install anaconda-client && bash ci-support/conda_upload.sh ; fi
