version: 2.0

checkout:
  post:
    - ./ci-support/checkout_merge_commit.sh

jobs:
  build:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run:
          name: debug
          command: |
            echo $PATH > path_file
            cat path_file
      - run:
          name: Pre install script for mac OS
          command: |
            bash ./ci-support/circleci_mac_machine_pre.sh
      - run:
          name: Install dependencies
          command: |
            bash ./ci-support/circleci_mac_dep.sh
      - run:
          name: Run tests
          command: |
            bash ./ci-support/circleci_mac.sh

      