package:
  name: vcdat
  version: 1.0.rc1

source:
  git_rev: v1.0.rc1
  git_url: git://github.com/CDAT/vcdat.git

requirements:
  build:
  - python
  - setuptools
  - nodejs
  run:
  - python
  - flask
  - vcs
  - cdms2
  - vcs-js
  - genutil
  - proj4 <5

build:
  noarch_python: true

about:
  home: http://github.com/CDAT/vcdat
