about:
  home: http://github.com/UV-CDAT/vcdat
package:
  name: vcdat
  version: "0.7.0"
requirements:
  build:
  - python=2
  - setuptools
  - nodejs
  run:
  - python=2
  - nodejs
  - flask
  - vcs
  - cdms2
  - cdutil
  - genutil
  - service_identity
  - vcsaddons
  - vcs-js
source:
  git_rev: v0.0.4
  git_url: git://github.com/UV-CDAT/vcdat.git
build:
  noarch_python: false
  number: 1
