about:
  home: http://gitub.com/UV-CDAT/vcdat
package:
  name: vcdat
  version: "0.0.1"
requirements:
  build:
  - python
  - setuptools
  - nodejs
  run:
  - python
  - flask
  - vcs
  - cdms2
  - vcs-js
  - cdutil
  - genutil
source:
  git_rev: v0.0.1
  git_url: git://github.com/UV-CDAT/vcdat.git
build:
  noarch_python: true
