about:
  home: http://gitub.com/UV-CDAT/vcdat
package:
  name: vcdat
  version: "0.0.3"
requirements:
  build:
  - python
  - setuptools
  - nodejs
  run:
  - python
  - flask
  - vcs
  - cdms2
  - cdutil
  - genutil
  - vcs-js
source:
  git_rev: v0.0.3
  git_url: git://github.com/UV-CDAT/vcdat.git
build:
  noarch_python: false
  number: 1
