about:
  home: http://gitub.com/UV-CDAT/vcdat
package:
  name: vcdat
  version: "0.0.2"
requirements:
  build:
  - python
  - setuptools
  - nodejs
  run:
  - python
  - flask
  - vcs 2.10
  - cdms2 2.10
  - cdutil 2.10
  - genutil 2.10
  - mesalib
  - vcs-js
source:
  git_rev: v0.0.2
  git_url: git://github.com/UV-CDAT/vcdat.git
build:
  # noarch_python: true
  number: 1
