about:
  home: http://gitub.com/UV-CDAT/vcdat
package:
  name: vcdat
  version: "0.0.4"
requirements:
  build:
  - python
  - setuptools
  - nodejs
  run:
  - python
  - flask
  - vcs 2.10
  - cdms2 2.10
  - cdutil 2.10
  - genutil 2.10
  - vcs-js
source:
  git_rev: v0.0.4
  git_url: git://github.com/UV-CDAT/vcdat.git
build:
  noarch_python: false
  number: 1
